name: Build LaTeX document
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Check for existing release
        id: check_release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: releases } = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const existingRelease = releases.find(release => release.tag_name === 'v1.0.0'); // Adjust tag name as needed
            return existingRelease ? existingRelease.id : null;

      - name: Create or update Release
        id: create_or_update_release
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.release_id) {
              await github.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: context.payload.release_id,
                tag_name: 'v1.0.0', // Adjust tag name as needed
                name: 'Release 1.0.0', // Adjust release name as needed
                draft: false,
                prerelease: false,
              });
            } else {
              const { data: release } = await github.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: 'v1.0.0', // Adjust tag name as needed
                name: 'Release 1.0.0', // Adjust release name as needed
                draft: false,
                prerelease: false,
              });
              core.setOutput('release_id', release.id);
            }

      - name: Upload PDF file
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_or_update_release.outputs.upload_url }}
          asset_path: main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
